In [1]:
from dldata.stimulus_sets.rust_datasets import Rust305ImageSet

Can't import h5py
Can't import separate mcc package
Can't import asgd.


/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/sklearn/lda.py:6: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be remov

In [2]:
rust_dldata = Rust305ImageSet()
rust_dldata

In [3]:
rust_dldata.get_images

<bound method Rust305ImageSet.get_images of <dldata.stimulus_sets.rust_datasets.Rust305ImageSet object at 0x7fd4ccd8f4d0>>

In [4]:
rust_dldata.neuronal_features_Rust

downloading http://dicarlocox-datasets.s3.amazonaws.com/Nicole305Images.tar.gz
getting Nicole305Images.tar.gz
Extracting '/Users/jjpr/.skdata/Rust305/Nicole305Images.tar.gz' to '/Users/jjpr/.skdata/Rust305'
 SHA-1 verification...
Progress:                    1 files extracted [ 0.3%] Progress:                    2 files extracted [ 0.7%] Progress:                    3 files extracted [ 1.0%] Progress:                    4 files extracted [ 1.3%] Progress:                    5 files extracted [ 1.6%] Progress:                    6 files extracted [ 2.0%] Progress:                    7 files extracted [ 2.3%] 

array([[ 3.4,  1.4,  2.6, ...,  0.6,  3.4,  1.2],
       [ 2.4,  0.8,  0.4, ...,  0.2,  4.4,  0.6],
       [ 3. ,  4.6,  2. , ...,  0.2,  3.6,  0. ],
       ..., 
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [5]:
rust_dldata.neuronal_features_Rust.shape

(305, 285)

In [6]:
rust_dldata.neuronal_features_reps_Rust

array([[[ 5.,  0.,  3., ...,  2.,  3.,  0.],
        [ 4.,  4.,  0., ...,  1.,  7.,  0.],
        [ 3.,  2.,  1., ...,  1.,  2.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  1.,  1., ...,  1.,  3.,  4.],
        [ 3.,  0.,  0., ...,  0.,  4.,  1.],
        [ 0.,  9.,  4., ...,  0.,  4.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 3.,  3.,  0., ...,  0.,  4.,  0.],
        [ 1.,  0.,  0., ...,  0.,  4.,  1.],
        [ 4.,  0.,  0., ...,  0.,  6.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 7.,  3.,  2., ...,  0.,  3.,  2.],
        [ 2.,  0.,  2., ...,  0.,  5.,  1.],
        [ 5.,  6.,  1., ...,  0.,  2.,  0.],
       

In [7]:
rust_dldata.neuronal_features_reps_Rust.shape

(5, 305, 285)

In [8]:
rust_dldata.meta

tabarray([(0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_1.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_2.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_3.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_4.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_5.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_6.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_7.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_8.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_9.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_10.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_11.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_12.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_13.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_14.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_15.png'),
       (0, '/Users/jjpr/.skdata/Rust305/imgs/Nat300_16.png'),
       (0, '/U

In [9]:
rust_dldata.meta.shape

(305,)

In [10]:
rust_dldata.categories

ValueError: no field of name category

In [11]:
len(rust_dldata.V4_NEURONS_Rust) + len(rust_dldata.IT_NEURONS_Rust)

285

In [12]:
rust_dldata.neuronal_features_HongMajaj

array([[[ -5.33891171e-02,  -2.14790478e-01,  -3.96035045e-01, ...,
          -7.33664855e-02,  -6.08853921e-02,  -5.11988215e-02],
        [ -4.71478747e-03,   6.12270050e-02,  -2.89594650e-01, ...,
           3.04466069e-01,   7.29426518e-02,  -4.08677477e-03],
        [ -5.14048934e-02,  -3.71085554e-01,   5.25749885e-02, ...,
           4.46521997e-01,  -4.44826484e-02,   2.66267627e-01],
        ..., 
        [  3.72134715e-01,   4.53326046e-01,  -2.58922465e-02, ...,
          -3.30886960e-01,  -1.13393329e-01,  -3.78079772e-01],
        [  5.09527802e-01,   5.41872323e-01,  -1.21891508e-02, ...,
          -2.16759875e-01,  -6.79848716e-02,  -3.36157441e-01],
        [  4.93807524e-01,   6.17800176e-01,  -9.44577008e-02, ...,
          -3.64653766e-01,  -1.08376168e-01,  -5.16396403e-01]],

       [[  1.55818081e-02,  -8.06559622e-02,  -7.50441849e-02, ...,
          -1.09351225e-01,  -8.62326026e-02,  -3.77958976e-02],
        [  2.51972079e-02,  -2.06611633e-01,  -1.43140286e-0

In [13]:
rust_dldata.neuronal_features_reps_Rust

array([[[ 5.,  0.,  3., ...,  2.,  3.,  0.],
        [ 4.,  4.,  0., ...,  1.,  7.,  0.],
        [ 3.,  2.,  1., ...,  1.,  2.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  1.,  1., ...,  1.,  3.,  4.],
        [ 3.,  0.,  0., ...,  0.,  4.,  1.],
        [ 0.,  9.,  4., ...,  0.,  4.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 3.,  3.,  0., ...,  0.,  4.,  0.],
        [ 1.,  0.,  0., ...,  0.,  4.,  1.],
        [ 4.,  0.,  0., ...,  0.,  6.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 7.,  3.,  2., ...,  0.,  3.,  2.],
        [ 2.,  0.,  2., ...,  0.,  5.,  1.],
        [ 5.,  6.,  1., ...,  0.,  2.,  0.],
       

In [14]:
rust_dldata.neuronal_features_reps_Rust.shape

(5, 305, 285)

In [15]:
type(rust_dldata.neuronal_features_reps_Rust)

numpy.ndarray

In [16]:
rust_dldata.neuronal_features_HongMajaj.shape

(6, 305, 296)

In [17]:
rust_dldata.neuronal_features_reps_HongMajaj

array([[[[ 0.10107411,  0.77067995, -0.54077649, ...,  1.16549253,
           1.89641881,  2.65558934],
         [-1.50388741, -0.2127572 , -0.22426471, ...,  0.08060717,
           0.67663604, -1.79039049],
         [ 0.10107411, -0.5405696 ,  0.72527063, ...,  0.44223565,
          -0.13655248, -0.67889565],
         ..., 
         [ 0.50231445,  0.44286755, -0.54077649, ..., -1.36590672,
          -0.13655248,  0.80309767],
         [ 1.30479515, -0.5405696 ,  0.09224706, ...,  0.44223565,
           0.27004179, -0.67889565],
         [-1.50388741,  0.11505517, -1.49031186, ..., -0.2810213 ,
          -0.54314673,  0.43259934]],

        [[-0.30016625, -0.5405696 , -0.22426471, ...,  1.52712095,
           0.67663604,  1.54409432],
         [-0.70140666,  0.11505517, -2.12333536, ...,  1.16549253,
          -0.54314673,  0.80309767],
         [-0.30016625, -1.19619429, -0.8572883 , ...,  0.80386406,
           0.67663604,  1.54409432],
         ..., 
         [ 0.10107411, -1.196194

In [18]:
rust_dldata.neuronal_features_reps_HongMajaj.shape

(6, 179, 305, 296)

In [19]:
import scipy.io as io

In [20]:
mat = io.loadmat("/Users/jjpr/.skdata/Rust305/Nicole305DataCollectedByNicole.mat")
mat

{'BLMIT': array([[[2, 1, 2, 0, 1],
         [1, 1, 0, 1, 3],
         [0, 0, 0, 0, 0],
         [0, 0, 1, 1, 2],
         [2, 1, 2, 1, 3]],
 
        [[0, 1, 0, 0, 0],
         [0, 0, 1, 2, 2],
         [0, 0, 0, 1, 0],
         [1, 0, 1, 0, 3],
         [1, 0, 0, 0, 1]],
 
        [[3, 3, 3, 0, 2],
         [5, 0, 1, 0, 0],
         [2, 1, 1, 2, 3],
         [1, 0, 1, 1, 1],
         [0, 1, 1, 0, 2]],
 
        ..., 
        [[0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0],
         [0, 1, 0, 1, 2],
         [1, 2, 0, 0, 0],
         [1, 2, 0, 0, 0]],
 
        [[4, 3, 5, 1, 4],
         [5, 5, 5, 2, 4],
         [3, 3, 4, 8, 4],
         [6, 5, 4, 6, 5],
         [4, 3, 6, 5, 8]],
 
        [[0, 1, 0, 0, 2],
         [0, 1, 0, 1, 0],
         [1, 2, 1, 1, 0],
         [2, 0, 1, 1, 0],
         [0, 2, 1, 0, 3]]], dtype=uint8),
 'BLMV4': array([[[ 0,  0,  3,  1,  0],
         [ 1,  0,  0,  0,  1],
         [ 0,  0,  3,  0,  3],
         [ 0,  0,  0,  1,  1],
         [ 1,  0,  0,  0,  3]],
 

In [21]:
type(mat)

dict

In [22]:
list(mat.keys())

['SpkMatV4',
 'SigMIT',
 'BLMIT',
 '__header__',
 '__globals__',
 'SigMV4',
 '__version__',
 'BLMV4',
 'SpkMatIT']

In [23]:
[(k, type(mat[k])) for k in mat]

[('SpkMatV4', numpy.ndarray),
 ('SigMIT', numpy.ndarray),
 ('BLMIT', numpy.ndarray),
 ('__header__', str),
 ('__globals__', list),
 ('SigMV4', numpy.ndarray),
 ('__version__', str),
 ('BLMV4', numpy.ndarray),
 ('SpkMatIT', numpy.ndarray)]

In [25]:
import numpy as np

In [26]:
[(k, mat[k].shape) for k in mat if type(mat[k]) is np.ndarray]

[('SpkMatV4', (143, 300, 5)),
 ('SigMIT', (1, 142)),
 ('BLMIT', (142, 5, 5)),
 ('SigMV4', (1, 143)),
 ('BLMV4', (143, 5, 5)),
 ('SpkMatIT', (142, 300, 5))]

In [27]:
import tables

In [28]:
h5 = tables.open_file("/Users/jjpr/.skdata/Rust305/Chabo_Tito_20130419_Nicole305_pooled_P58.trim.wh.evoked.repr.h5")
h5

File(filename=/Users/jjpr/.skdata/Rust305/Chabo_Tito_20130419_Nicole305_pooled_P58.trim.wh.evoked.repr.h5, title='', mode='r', root_uep='/', filters=Filters(complevel=0, shuffle=False, bitshuffle=False, fletcher32=False, least_significant_digit=None))
/ (RootGroup) ''
/spk (CArray(6, 179, 305, 296), shuffle, blosc(4)) ''
  atom := Float32Atom(shape=(), dflt=0.0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := (1, 1, 221, 296)
/meta (Group) 'Metadata'
/meta/idx2iid (Array(305,)) ''
  atom := StringAtom(itemsize=12, shape=(), dflt='')
  maindim := 0
  flavor := 'python'
  byteorder := 'irrelevant'
  chunkshape := None
/meta/idx2iid_pk (Array()) ''
  atom := StringAtom(itemsize=6502, shape=(), dflt='')
  maindim := 0
  flavor := 'python'
  byteorder := 'irrelevant'
  chunkshape := None
/meta/idx2lbl (Array(6, 2)) ''
  atom := Int64Atom(shape=(), dflt=0)
  maindim := 0
  flavor := 'python'
  byteorder := 'little'
  chunkshape := None
/meta/idx2lbl_pk (Array()) ''

In [33]:
h5.root.meta.idx2lbl[:]

[[70, 170], [50, 100], [100, 150], [150, 200], [200, 250], [70, 270]]

In [48]:
for node in h5.walk_nodes():
  if isinstance(node, tables.Leaf):
    print(node._v_name)
    print(node)
    if len(node.shape) < 3:
      print(node.read())
    print

spk
/spk (CArray(6, 179, 305, 296), shuffle, blosc(4)) ''

idx2iid
/meta/idx2iid (Array(305,)) ''
['Nat300_F_1', 'Nat300_F_2', 'Nat300_F_3', 'Nat300_F_4', 'Nat300_F_5', 'Nat300_F_6', 'Nat300_F_7', 'Nat300_F_8', 'Nat300_F_9', 'Nat300_F_10', 'Nat300_F_11', 'Nat300_F_12', 'Nat300_F_13', 'Nat300_F_14', 'Nat300_F_15', 'Nat300_F_16', 'Nat300_F_17', 'Nat300_F_18', 'Nat300_F_19', 'Nat300_F_20', 'Nat300_F_21', 'Nat300_F_22', 'Nat300_F_23', 'Nat300_F_24', 'Nat300_F_25', 'Nat300_F_26', 'Nat300_F_27', 'Nat300_F_28', 'Nat300_F_29', 'Nat300_F_30', 'Nat300_F_31', 'Nat300_F_32', 'Nat300_F_33', 'Nat300_F_34', 'Nat300_F_35', 'Nat300_F_36', 'Nat300_F_37', 'Nat300_F_38', 'Nat300_F_39', 'Nat300_F_40', 'Nat300_F_41', 'Nat300_F_42', 'Nat300_F_43', 'Nat300_F_44', 'Nat300_F_45', 'Nat300_F_46', 'Nat300_F_47', 'Nat300_F_48', 'Nat300_F_49', 'Nat300_F_50', 'Nat300_F_51', 'Nat300_F_52', 'Nat300_F_53', 'Nat300_F_54', 'Nat300_F_55', 'Nat300_F_56', 'Nat300_F_57', 'Nat300_F_58', 'Nat300_F_59', 'Nat300_F_60', 'Nat300_F_

In [44]:
h5.root.meta.orgfile[0, 0, 0, :]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 33, 33, 33, 33, 33, 33, 33,
       33, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
       30, 30, 30, 30, 30

In [46]:
(h5.root.meta.orgfile.shape)

(6, 179, 305, 296)

In [49]:
import pandas as pd

In [50]:
df_meta = pd.DataFrame(rust_dldata.meta)
df_meta

blank                                         filename
0        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_1.png
1        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_2.png
2        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_3.png
3        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_4.png
4        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_5.png
5        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_6.png
6        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_7.png
7        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_8.png
8        0    /Users/jjpr/.skdata/Rust305/imgs/Nat300_9.png
9        0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_10.png
10       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_11.png
11       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_12.png
12       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_13.png
13       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_14.png
14       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_15.png
15       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_16.png
16       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_17.png
17       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_18.png
18       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_19.png
19       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_20.png
20       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_21.png
21       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_22.png
22       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_23.png
23       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_24.png
24       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_25.png
25       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_26.png
26       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_27.png
27       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_28.png
28       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_29.png
29       0   /Users/jjpr/.skdata/Rust305/imgs/Nat300_30.png
..     ...                                              ...
275      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_276.png
276      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_277.png
277      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_278.png
278      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_279.png
279      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_280.png
280      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_281.png
281      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_282.png
282      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_283.png
283      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_284.png
284      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_285.png
285      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_286.png
286      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_287.png
287      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_288.png
288      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_289.png
289      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_290.png
290      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_291.png
291      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_292.png
292      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_293.png
293      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_294.png
294      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_295.png
295      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_296.png
296      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_297.png
297      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_298.png
298      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_299.png
299      0  /Users/jjpr/.skdata/Rust305/imgs/Nat300_300.png
300      1  /Users/jjpr/.skdata/Rust305/imgs/Nat300_301.png
301      1  /Users/jjpr/.skdata/Rust305/imgs/Nat300_302.png
302      1  /Users/jjpr/.skdata/Rust305/imgs/Nat300_303.png
303      1  /Users/jjpr/.skdata/Rust305/imgs/Nat300_304.png
304      1  /Users/jjpr/.skdata/Rust305/imgs/Nat300_305.png

[305 rows x 2 columns]

In [57]:
import hashlib
import os
def sha1_hash(path, buffer_size=64 * 2 ** 10):
    sha1 = hashlib.sha1()
    with open(path, "rb") as f:
        buffer = f.read(buffer_size)
        while len(buffer) > 0:
            sha1.update(buffer)
            buffer = f.read(buffer_size)
    return sha1.hexdigest()

In [51]:
def get_coords_stimulus(dataset):
    df_meta = pd.DataFrame(dataset.meta)
    df_meta["image_id"] = [sha1_hash(path) for path in df_meta["filename"]]
    df_meta["filename"] = df_meta["filename"].apply(os.path.basename)
    df_meta = df_meta.rename(columns={"blank": "is_blank"})
    coords_stimulus = {col: ("stimulus", df_meta[col]) for col in df_meta}
    return coords_stimulus

In [58]:
get_coords_stimulus(rust_dldata)

{'filename': ('stimulus', 0        Nat300_1.png
  1        Nat300_2.png
  2        Nat300_3.png
  3        Nat300_4.png
  4        Nat300_5.png
  5        Nat300_6.png
  6        Nat300_7.png
  7        Nat300_8.png
  8        Nat300_9.png
  9       Nat300_10.png
  10      Nat300_11.png
  11      Nat300_12.png
  12      Nat300_13.png
  13      Nat300_14.png
  14      Nat300_15.png
  15      Nat300_16.png
  16      Nat300_17.png
  17      Nat300_18.png
  18      Nat300_19.png
  19      Nat300_20.png
  20      Nat300_21.png
  21      Nat300_22.png
  22      Nat300_23.png
  23      Nat300_24.png
  24      Nat300_25.png
  25      Nat300_26.png
  26      Nat300_27.png
  27      Nat300_28.png
  28      Nat300_29.png
  29      Nat300_30.png
              ...      
  275    Nat300_276.png
  276    Nat300_277.png
  277    Nat300_278.png
  278    Nat300_279.png
  279    Nat300_280.png
  280    Nat300_281.png
  281    Nat300_282.png
  282    Nat300_283.png
  283    Nat300_284.png
  284    Nat300_

In [61]:
v4 = rust_dldata.V4_NEURONS_Rust
it = rust_dldata.IT_NEURONS_Rust
regions = [""] * (len(v4) + len(it))
for i in v4:
  regions[i] = "V4"
for i in it:
  regions[i] = "IT"
len(regions), regions

(285,
 ['V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  'V4',
  

In [64]:
ids = ["rust305.single.{:02d}".format(i) for i in range(rust_dldata.neuronal_features_reps_Rust.shape[2])]
ids

['rust305.single.00',
 'rust305.single.01',
 'rust305.single.02',
 'rust305.single.03',
 'rust305.single.04',
 'rust305.single.05',
 'rust305.single.06',
 'rust305.single.07',
 'rust305.single.08',
 'rust305.single.09',
 'rust305.single.10',
 'rust305.single.11',
 'rust305.single.12',
 'rust305.single.13',
 'rust305.single.14',
 'rust305.single.15',
 'rust305.single.16',
 'rust305.single.17',
 'rust305.single.18',
 'rust305.single.19',
 'rust305.single.20',
 'rust305.single.21',
 'rust305.single.22',
 'rust305.single.23',
 'rust305.single.24',
 'rust305.single.25',
 'rust305.single.26',
 'rust305.single.27',
 'rust305.single.28',
 'rust305.single.29',
 'rust305.single.30',
 'rust305.single.31',
 'rust305.single.32',
 'rust305.single.33',
 'rust305.single.34',
 'rust305.single.35',
 'rust305.single.36',
 'rust305.single.37',
 'rust305.single.38',
 'rust305.single.39',
 'rust305.single.40',
 'rust305.single.41',
 'rust305.single.42',
 'rust305.single.43',
 'rust305.single.44',
 'rust305.

In [8]:
start, end = zip(*rust_dldata.TIMEBINS_HongMajaj)
(start, end)

((70, 50, 100, 150, 200, 70), (170, 100, 150, 200, 250, 270))

In [9]:
rust_dldata.neuronal_features_reps_HongMajaj

array([[[[ 0.10107411,  0.77067995, -0.54077649, ...,  1.16549253,
           1.89641881,  2.65558934],
         [-1.50388741, -0.2127572 , -0.22426471, ...,  0.08060717,
           0.67663604, -1.79039049],
         [ 0.10107411, -0.5405696 ,  0.72527063, ...,  0.44223565,
          -0.13655248, -0.67889565],
         ..., 
         [ 0.50231445,  0.44286755, -0.54077649, ..., -1.36590672,
          -0.13655248,  0.80309767],
         [ 1.30479515, -0.5405696 ,  0.09224706, ...,  0.44223565,
           0.27004179, -0.67889565],
         [-1.50388741,  0.11505517, -1.49031186, ..., -0.2810213 ,
          -0.54314673,  0.43259934]],

        [[-0.30016625, -0.5405696 , -0.22426471, ...,  1.52712095,
           0.67663604,  1.54409432],
         [-0.70140666,  0.11505517, -2.12333536, ...,  1.16549253,
          -0.54314673,  0.80309767],
         [-0.30016625, -1.19619429, -0.8572883 , ...,  0.80386406,
           0.67663604,  1.54409432],
         ..., 
         [ 0.10107411, -1.196194

In [10]:
rust_dldata.neuronal_features_reps_HongMajaj.shape

(6, 179, 305, 296)

In [12]:
import xarray as xr

In [16]:
loaded = xr.open_dataarray("/Users/jjpr/dev/dldata/scripts/rust_single.nc")
loaded

<xarray.DataArray (neuroid: 285, presentation: 1525, time_bin: 1)>
[434625 values with dtype=float64]
Coordinates:
    neuroid_id  (neuroid) |S18 'rust305.single.000' 'rust305.single.001' ...
    image_id    (presentation) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 ...
    region      (neuroid) |S2 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' ...
    repetition  (presentation) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Dimensions without coordinates: neuroid, presentation, time_bin

In [15]:
loaded["blank"]

KeyError: 'blank'

In [19]:
loaded[:, 0:0, :]

<xarray.DataArray (neuroid: 285, presentation: 0, time_bin: 1)>
array([], shape=(285, 0, 1), dtype=float64)
Coordinates:
    neuroid_id  (neuroid) |S18 'rust305.single.000' 'rust305.single.001' ...
    image_id    (presentation) int64 
    region      (neuroid) |S2 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' ...
    repetition  (presentation) int64 
Dimensions without coordinates: neuroid, presentation, time_bin

In [20]:
loaded["repetition"]==0

<xarray.DataArray 'repetition' (presentation: 1525)>
array([ True,  True,  True, ..., False, False, False], dtype=bool)
Coordinates:
    image_id    (presentation) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 ...
    repetition  (presentation) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Dimensions without coordinates: presentation

In [22]:
loaded[:, loaded["repetition"]==0, :]

<xarray.DataArray (neuroid: 285, presentation: 305, time_bin: 1)>
array([[[  1.464177e-312],
        [  1.485397e-312],
        ..., 
        [  1.421737e-312],
        [  1.442957e-312]],

       [[  1.464177e-312],
        [  1.485397e-312],
        ..., 
        [  1.421737e-312],
        [  1.442957e-312]],

       ..., 
       [[  1.787012e-307],
        [  1.783536e-307],
        ..., 
        [  0.000000e+000],
        [  1.792227e-307]],

       [[  1.787012e-307],
        [  1.783536e-307],
        ..., 
        [  0.000000e+000],
        [  1.792227e-307]]])
Coordinates:
    neuroid_id  (neuroid) |S18 'rust305.single.000' 'rust305.single.001' ...
    image_id    (presentation) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 ...
    region      (neuroid) |S2 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' 'V4' ...
    repetition  (presentation) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Dimensions without coordinates: neuroid, presentation, time_bin

In [23]:
(len(rust_dldata.V4_NEURONS_Rust), len(rust_dldata.IT_NEURONS_Rust))

(143, 142)

In [24]:
from dldata.physiology.hongmajaj import mappings

In [25]:
v4_chabo = mappings.LST_V4_Chabo
it_chabo = mappings.LST_IT_Chabo
v4_tito = mappings.LST_V4_Tito
it_tito = mappings.LST_IT_Tito
(len(v4_chabo), len(it_chabo), len(v4_tito), len(it_tito))

(70, 58, 58, 110)

In [26]:
(len(v4_chabo) + len(v4_tito), len(it_chabo) + len(it_tito))

(128, 168)