In [1]:
import numpy as np
import pandas as pd
import xarray as xr

In [13]:
import mkgu
from mkgu import metrics

In [3]:
hvm = mkgu.get_assembly(name="HvM")
hvm

<xarray.NeuronRecordingAssembly 'dataset_hvm' (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.808021],
        [ 1.555112],
        ..., 
        [-0.200395],
        [ 0.951983]],

       [[-0.386136],
        [-0.725592],
        ..., 
        [ 0.050503],
        [ 0.742559]],

       ..., 
       [[ 0.822267],
        [ 0.224162],
        ..., 
        [ 1.634816],
        [ 0.800551]],

       [[-0.923935],
        [-0.923935],
        ..., 
        [ 0.265927],
        [-0.603347]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - y               (neuroid) float64 0.2 0.6 0.2 1.0 0.6 1.0 1.8 1.0 1.8 ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - row             (neuroid) int64 5 6 5 7 6 7 9 7 9 8 9 2 1 3 6 7 6 6 8 5 ...
  - animal          (neuroid) object 'Chabo' 'Chabo' 'Chabo' 'Chabo' 'Chabo' ...
  - x               (

In [4]:
hvm.load()

<xarray.NeuronRecordingAssembly 'dataset_hvm' (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.808021],
        [ 1.555112],
        ..., 
        [-0.200395],
        [ 0.951983]],

       [[-0.386136],
        [-0.725592],
        ..., 
        [ 0.050503],
        [ 0.742559]],

       ..., 
       [[ 0.822267],
        [ 0.224162],
        ..., 
        [ 1.634816],
        [ 0.800551]],

       [[-0.923935],
        [-0.923935],
        ..., 
        [ 0.265927],
        [-0.603347]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - y               (neuroid) float64 0.2 0.6 0.2 1.0 0.6 1.0 1.8 1.0 1.8 ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - row             (neuroid) int64 5 6 5 7 6 7 9 7 9 8 9 2 1 3 6 7 6 6 8 5 ...
  - animal          (neuroid) object 'Chabo' 'Chabo' 'Chabo' 'Chabo' 'Chabo' ...
  - x               (

In [7]:
dim = "presentation"
fraction = 0.01
indices = sorted(np.random.choice(hvm.sizes[dim], int(hvm.sizes[dim]*fraction), replace=False))
d = {dim: indices}
hvm_small = hvm.isel(**d)
hvm_small

<xarray.NeuronRecordingAssembly 'dataset_hvm' (neuroid: 296, presentation: 2688, time_bin: 1)>
array([[[ 1.181566],
        [-0.312616],
        ..., 
        [-0.584208],
        [ 0.951983]],

       [[-1.065048],
        [-1.065048],
        ..., 
        [-0.964253],
        [-0.281528]],

       ..., 
       [[ 1.420371],
        [ 0.523214],
        ..., 
        [ 0.801944],
        [-0.879624]],

       [[ 0.291163],
        [-0.923935],
        ..., 
        [-0.374007],
        [-1.566836]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - y               (neuroid) float64 0.2 0.6 0.2 1.0 0.6 1.0 1.8 1.0 1.8 ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - row             (neuroid) int64 5 6 5 7 6 7 9 7 9 8 9 2 1 3 6 7 6 6 8 5 ...
  - animal          (neuroid) object 'Chabo' 'Chabo' 'Chabo' 'Chabo' 'Chabo' ...
  - x               (ne

In [8]:
hvm_it_v6 = hvm_small.sel(var="V6").sel(region="IT")
hvm_it_v6

<xarray.NeuronRecordingAssembly 'dataset_hvm' (neuroid: 168, presentation: 1231, time_bin: 1)>
array([[[ 0.121288],
        [-0.259774],
        ..., 
        [-0.584208],
        [ 0.951983]],

       [[ 0.512693],
        [-1.45123 ],
        ..., 
        [-0.964253],
        [-0.281528]],

       ..., 
       [[ 2.235602],
        [ 0.36414 ],
        ..., 
        [ 1.135502],
        [ 0.592418]],

       [[ 0.65738 ],
        [ 1.32948 ],
        ..., 
        [ 1.707068],
        [ 1.402507]]], dtype=float32)
Coordinates:
  * neuroid         (neuroid) MultiIndex
  - arr             (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - y               (neuroid) float64 0.2 0.6 0.2 1.0 0.6 1.0 1.8 1.0 1.8 ...
  - col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 8 8 6 7 5 7 7 6 6 ...
  - row             (neuroid) int64 5 6 5 7 6 7 9 7 9 8 9 8 9 6 8 7 9 7 9 7 ...
  - animal          (neuroid) object 'Chabo' 'Chabo' 'Chabo' 'Chabo' 'Chabo' ...
  - x               (ne

In [9]:
group_coord_names = ["category", "obj"]
hvm_it_v6_grp = hvm_it_v6.multi_groupby(group_coord_names)
hvm_it_v6_grp

In [16]:
hvm_it_v6_obj = hvm_it_v6_grp.mean(dim=dim).squeeze("time_bin").T
assert hvm_it_v6_obj.shape == (64, 168)
hvm_it_v6_obj

<xarray.NeuronRecordingAssembly 'dataset_hvm' (presentation: 64, neuroid: 168)>
array([[ 0.09894 , -0.501152, -0.403668, ...,  0.250164, -0.04273 ,  0.192469],
       [-0.103032, -0.133342,  0.451318, ..., -0.050875,  0.268036,  0.350942],
       [-0.372253, -0.059222,  0.214954, ...,  0.415837,  0.345803,  0.359539],
       ..., 
       [-0.063616,  0.02294 , -0.052702, ..., -0.003976, -0.099993, -0.172002],
       [ 0.022207, -0.161085,  0.026367, ..., -0.179097, -0.083223,  0.063371],
       [ 0.461849,  0.240808, -0.182985, ..., -0.424621,  0.028327,  0.060863]], dtype=float32)
Coordinates:
  * neuroid       (neuroid) MultiIndex
  - arr           (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - y             (neuroid) float64 0.2 0.6 0.2 1.0 0.6 1.0 1.8 1.0 1.8 1.4 ...
  - col           (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 8 8 6 7 5 7 7 6 6 5 ...
  - row           (neuroid) int64 5 6 5 7 6 7 9 7 9 8 9 8 9 6 8 7 9 7 9 7 9 ...
  - animal        (neuroid) object 'Chab

In [17]:
rdm_hvm = metrics.RDM()
bmk_hvm = metrics.Benchmark(rdm_hvm, hvm_it_v6_obj)
rdm = bmk_hvm.calculate()
assert rdm.shape == (64, 64)
rdm

array([[ 1.        ,  0.12883963,  0.19493496, ..., -0.03996762,
        -0.18731509, -0.14668575],
       [ 0.12883963,  1.        ,  0.1175529 , ...,  0.14366373,
         0.14501458,  0.15428576],
       [ 0.19493496,  0.1175529 ,  1.        , ..., -0.09805924,
        -0.20979389, -0.17942924],
       ..., 
       [-0.03996762,  0.14366373, -0.09805924, ...,  1.        ,
         0.19866627,  0.22339773],
       [-0.18731509,  0.14501458, -0.20979389, ...,  0.19866627,
         1.        ,  0.19626698],
       [-0.14668575,  0.15428576, -0.17942924, ...,  0.22339773,
         0.19626698,  1.        ]])