In [1]:
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
import mkgu
from mkgu.metrics.rdm import RSA

In [3]:
hvm = mkgu.get_assembly(name="dicarlo.Majaj2015")
hvm

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ..., 
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ..., 
        [ 2.449372],
        [ 0.401197]],

       ..., 
       [[ 1.121319],
        [ 1.719423],
        ..., 
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ..., 
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo'

In [4]:
hvm_stimulus = hvm.attrs["stimulus_set"]
hvm_stimulus

id                                  image_id  \
0        1  8a72e2bfdb8c267b57232bf96f069374d5b21832   
1        2  27f69468c9d6019ed0d22b9583c94c5b58198c1c   
2        3  6af1cbb28aacea6c582faa07e92d8325fa7a29d7   
3        4  d0f7a45b377d4920c3466ec7a20dce9437a150d6   
4        5  d4c3b4d4aefd29fd168a2c3c9a9962d99653a715   
5        6  c6fb4f35719f0f205f5ad65f4fd2794212c5d139   
6        7  ae2b8aac003c867a772647197dcd3c050b75a06e   
7        8  a7a31e65e2770c7a503988835c24aeab689abf47   
8        9  09d2924723bc4677df666072b6e25e988d5f0668   
9       10  1df484a50ff7fbd85112990b7f8fe616c49adb28   
10      11  e134c3d8fa8be11c8eb0b8d55e7f534286f44736   
11      12  6997bb3d5bef2f6f9d6cfbdcaab1444680a44cb0   
12      13  fbef152524d2e593206fd976afde5e0506f477a8   
13      14  a17db26a610f96215d94cd673fd982c5bb3fd524   
14      15  41e376452bcb4a61646304b4fd397f11e329ebb2   
15      16  36b1652f43aedf23e39f351fd931ab0cb4c410b5   
16      17  6a8b93cd59587cc2969a126361bce879774e7f4f   
17      18  05954905d976ab1cf247c49fc31e534a8a047ba1   
18      19  97757502b8c2e32e47a79a266f2da46bbb7165d1   
19      20  45b221ea1ed093c991ba6503c57093f6bea2c9d7   
20      21  f680c591330f26793f4de603e26cc584ae19ddb2   
21      22  a2de393bdfbaaa69500cc1b0d1bfe0f37c6459e1   
22      23  f4fe19dc937fb33d9439fc99f4ea17fc76591e36   
23      24  dd8ff3ddeac872a646b02b8fdcf286c87cdd7720   
24      25  3d31939c0fbbb695d865f3e010d9860b65c674f2   
25      26  88429363542db8c918d7112a7335fcca62966a3e   
26      27  1d832e0abdd6266fb3dcacfa05df1725d6b08fb7   
27      28  b54f9e7fbc9f49bb60f6d24aa9e90b7623a4b42d   
28      29  6e2ddadd2ca093f7638282e4851b60d5b87b8ca4   
29      30  a533e519b553cdf360ae134f7c9f161134ddaf00   
...    ...                                       ...   
5730  5731  fd135a1c5e2b157b4557ef8473681ca6d03b0188   
5731  5732  6b87003f02400681dc545c7cd57cde747c1cb98a   
5732  5733  a051580c645ed432381d24beb6e93ee7952c8334   
5733  5734  a8648457a08c568c907c68d058e2d33bb276a71e   
5734  5735  241a33fd5221263ac3d350bd82ddeab2d0104eab   
5735  5736  81445f4ea46ae937d1b94f93f5e9a475dc6e0817   
5736  5737  51ba24371f3c0683da1978d332184732bbec5b96   
5737  5738  88f954276bb53915429cc2d117e57c08bc8aaddd   
5738  5739  d2af56088e557fbafc9815e9a7486f3efe61823e   
5739  5740  d4dd9a086994a89bf6e2d32efab254bdd4648888   
5740  5741  30912859b0dfac9c6531061a796fb96f16510fa8   
5741  5742  8b85fdd6295e9fa10c1230edd6ea63a038ceb15e   
5742  5743  518d256ccedbcda049049c1183bc30ff2aa93258   
5743  5744  98cc0d8f063fae1b0c22645f384875ec0f73212c   
5744  5745  fd18b1f8ca6d961c163aa56772d813f6cba28336   
5745  5746  5650c755edcbeb39a1d8b848128bd52e97a3c2c2   
5746  5747  10a6a9b7b8a5a83708417f4feebe7f12eee6ecec   
5747  5748  d15aa059b0180b200fb82fb8039247c3b53f9d66   
5748  5749  bb2ca2aeb9a7996ef849aeca2388fece5d66dd58   
5749  5750  af8325d2d77b8475a00eb9a5296689adb4a8f39b   
5750  5751  5cbd24a0ac1881551f356940236e021bd29cd1de   
5751  5752  feef7d8cf74ce5f8a8d0612e015e0de363587e93   
5752  5753  6f61f7e3130d2fef3deeb310e08a927521cb932d   
5753  5754  43fe5ff454d4b4c615f8b44f625c6f8a9cd7d501   
5754  5755  3fe99701f03c85d5b2017d4ec33eb227a695386e   
5755  5756  06a3f98dc29129a672ab2af8b5b02d3a2cc82a85   
5756  5757  2c381c66bf457942bf4818e54b4b5172b3cc0cac   
5757  5758  d6a597127092d38ed37bcb19967075698acb35ee   
5758  5759  cc975ea997317b74a79b9f5568f8008acdec341e   
5759  5760  e35071a43f7a0dafc21b18229ca36f1940c2c567   

                                        image_file_name object_name  \
0     astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_...   car_astra   
1     _12_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty...      table3   
2     face0003_rx+00.000_ry+00.000_rz+00.000_tx+00.0...       face2   
3     walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00...      walnut   
4     walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00...      walnut   
5     sopwith_rx+00.000_ry+00.000_rz+00.000_tx+00.00...   airplane7   
6     Apricot_obj_rx-90.000_ry+00.000_

In [5]:
hvm_stimulus.image_paths

{'8a72e2bfdb8c267b57232bf96f069374d5b21832': '/Users/jjpr/.mkgu/data/dicarlo.hvm/Variation00_20110203/astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+01.000_ecd40f3f6d7a4d6d88134d648884e0b9b364efc9_256x256.png',
 '27f69468c9d6019ed0d22b9583c94c5b58198c1c': '/Users/jjpr/.mkgu/data/dicarlo.hvm/Variation00_20110203/_12_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+00.700_006d66c207c6417574f62f0560c6b2b40a9ec5a1_256x256.png',
 '6af1cbb28aacea6c582faa07e92d8325fa7a29d7': '/Users/jjpr/.mkgu/data/dicarlo.hvm/Variation00_20110203/face0003_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+00.800_3b3c1d65865028d0fad0b0bf8f305098db717e7f_256x256.png',
 'd0f7a45b377d4920c3466ec7a20dce9437a150d6': '/Users/jjpr/.mkgu/data/dicarlo.hvm/Variation00_20110203/walnut_obj_rx-90.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+00.700_687ade2f9ee4d52af9705865395471a24ba38d5f_256x256.png',
 'd4c3b4d4aefd29fd168a2c3c9a9962d99653a715': '/Users/jjpr/.mkgu/data/dicarlo.hvm/Variation00_20110203/waln

In [6]:
hvm_stimulus.get_image("8a72e2bfdb8c267b57232bf96f069374d5b21832")

'/Users/jjpr/.mkgu/data/dicarlo.hvm/Variation00_20110203/astra_rx+00.000_ry+00.000_rz+00.000_tx+00.000_ty+00.000_s+01.000_ecd40f3f6d7a4d6d88134d648884e0b9b364efc9_256x256.png'

In [7]:
hvm.load() # This loads all data into memory instead of lazily fetching from disk

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ..., 
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ..., 
        [ 2.449372],
        [ 0.401197]],

       ..., 
       [[ 1.121319],
        [ 1.719423],
        ..., 
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ..., 
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo'

In [8]:
hvm_it_v6 = hvm.sel(variation=6).sel(region="IT")
hvm_it_v6

<xarray.NeuronRecordingAssembly (neuroid: 168, presentation: 120320, time_bin: 1)>
array([[[ 0.121288],
        [-1.784021],
        ..., 
        [-0.968256],
        [ 0.183887]],

       [[ 0.512693],
        [ 0.512693],
        ..., 
        [ 2.449372],
        [ 0.401197]],

       ..., 
       [[-0.384445],
        [-0.384445],
        ..., 
        [-0.377575],
        [-0.393541]],

       [[-1.358922],
        [ 1.665531],
        ..., 
        [ 0.208243],
        [-0.358707]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 8 8 6 7 5 7 7 6 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo'

In [9]:
dim = "presentation"
group_coord_names = ["category_name", "object_name"]
hvm_it_v6_grp = hvm_it_v6.multi_groupby(group_coord_names)
hvm_it_v6_obj = hvm_it_v6_grp.mean(dim=dim).squeeze("time_bin").T
assert hvm_it_v6_obj.shape == (64, 168)
hvm_it_v6_obj

<xarray.NeuronRecordingAssembly (presentation: 64, neuroid: 168)>
array([[ 0.087381, -0.035234,  0.16607 , ..., -0.083298, -0.04096 ,  0.009889],
       [ 0.10009 ,  0.07415 ,  0.136218, ...,  0.049036, -0.040681, -0.049637],
       [ 0.196117,  0.095425, -0.012496, ...,  0.088381, -0.079695,  0.023809],
       ..., 
       [ 0.03505 ,  0.009078, -0.098099, ..., -0.030416, -0.081772, -0.185693],
       [ 0.065006,  0.072046, -0.032077, ..., -0.127431, -0.025176, -0.034318],
       [ 0.102832,  0.102089,  0.089803, ..., -0.055868, -0.108431, -0.083379]], dtype=float32)
Coordinates:
  * neuroid        (neuroid) MultiIndex
  - neuroid_id     (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr            (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col            (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 8 8 6 7 5 7 7 6 6 5 ...
  - hemisphere     (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion      (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT'

In [10]:
rsa_characterization = RSA()
rsa = rsa_characterization(hvm_it_v6_obj)
assert list(rsa.shape) == [64, 64]
rsa

<xarray.DataAssembly (presentation: 64)>
array([[ 1.      ,  0.53554 ,  0.687936, ...,  0.47855 ,  0.618492,  0.551413],
       [ 0.53554 ,  1.      ,  0.438187, ...,  0.303748,  0.413138,  0.359837],
       [ 0.687936,  0.438187,  1.      , ...,  0.348462,  0.232529,  0.262504],
       ..., 
       [ 0.47855 ,  0.303748,  0.348462, ...,  1.      ,  0.332639,  0.275846],
       [ 0.618492,  0.413138,  0.232529, ...,  0.332639,  1.      ,  0.549457],
       [ 0.551413,  0.359837,  0.262504, ...,  0.275846,  0.549457,  1.      ]])
Coordinates:
    time_bin       object (70, 170)
  * presentation   (presentation) MultiIndex
  - category_name  (presentation) object 'Animals' 'Animals' 'Animals' ...
  - object_name    (presentation) object 'bear' 'cow' 'dog' 'elephant' ...