In [1]:
import string
import numpy as np
import xarray as xr

In [2]:
da1 = xr.DataArray(np.random.randn(2, 3), [('x', ['a', 'b']), ('y', [10, 20, 30])])
da1

<xarray.DataArray (x: 2, y: 3)>
array([[-0.507435, -1.19325 , -0.144582],
       [ 0.258848, -0.71531 , -0.683058]])
Coordinates:
  * x        (x) <U1 'a' 'b'
  * y        (y) int64 10 20 30

In [3]:
da2 = xr.DataArray(np.random.randn(2, 3), [('x', ['c', 'd']), ('y', [40, 50, 60])])
da2

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.951908,  2.19363 ,  0.800204],
       [ 0.060204, -1.334579,  0.421212]])
Coordinates:
  * x        (x) <U1 'c' 'd'
  * y        (y) int64 40 50 60

In [4]:
da3 = xr.DataArray(np.random.randn(2, 2), [('x', ['b', 'c']), ('y', [30, 40])])
da3

<xarray.DataArray (x: 2, y: 2)>
array([[-0.530381,  0.584825],
       [-0.220513,  1.550545]])
Coordinates:
  * x        (x) <U1 'b' 'c'
  * y        (y) int64 30 40

In [5]:
xr.align(da1, da2, join="outer")

(<xarray.DataArray (x: 4, y: 6)>
 array([[-0.507435, -1.19325 , -0.144582,       nan,       nan,       nan],
        [ 0.258848, -0.71531 , -0.683058,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,  0.951908,  2.19363 ,  0.800204],
        [      nan,       nan,       nan,  0.060204, -1.334579,  0.421212]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60)

In [6]:
xr.align(da1, da2, da3, join="outer")

(<xarray.DataArray (x: 4, y: 6)>
 array([[-0.507435, -1.19325 , -0.144582,       nan,       nan,       nan],
        [ 0.258848, -0.71531 , -0.683058,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,       nan,       nan,  0.951908,  2.19363 ,  0.800204],
        [      nan,       nan,       nan,  0.060204, -1.334579,  0.421212]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 4, y: 6)>
 array([[      nan,       nan,       nan,       nan,       nan,       nan],
        [      nan,  

In [7]:
xr.concat(xr.align(da1, da2, da3, join="outer"), dim="y")

<xarray.DataArray (x: 4, y: 18)>
array([[-0.507435, -1.19325 , -0.144582,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan],
       [ 0.258848, -0.71531 , -0.683058,       nan,       nan,       nan,
              nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan, -0.530381,  0.584825,       nan,       nan],
       [      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,  0.951908,  2.19363 ,  0.800204,
              nan,       nan, -0.220513,  1.550545,       nan,       nan],
       [      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan,  0.060204, -1.334579,  0.421212,
              nan,       nan,       nan,       nan,       nan,       nan]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int6

In [8]:
xr.merge([da1, da2, da3])

ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name

In [9]:
xr.merge(xr.align(da1, da2, da3, join="outer"))

ValueError: unable to convert unnamed DataArray to a Dataset without providing an explicit name

In [10]:
da1.combine_first(da2)

<xarray.DataArray (x: 4, y: 6)>
array([[-0.507435, -1.19325 , -0.144582,       nan,       nan,       nan],
       [ 0.258848, -0.71531 , -0.683058,       nan,       nan,       nan],
       [      nan,       nan,       nan,  0.951908,  2.19363 ,  0.800204],
       [      nan,       nan,       nan,  0.060204, -1.334579,  0.421212]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [11]:
da1.combine_first(da3)

<xarray.DataArray (x: 3, y: 4)>
array([[-0.507435, -1.19325 , -0.144582,       nan],
       [ 0.258848, -0.71531 , -0.683058,  0.584825],
       [      nan,       nan, -0.220513,  1.550545]])
Coordinates:
  * x        (x) object 'a' 'b' 'c'
  * y        (y) int64 10 20 30 40

In [12]:
da1.name = "da1"
da2.name = "da2"
da3.name = "da3"

In [13]:
xr.merge([da1, da2, da3])

<xarray.Dataset>
Dimensions:  (x: 4, y: 6)
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60
Data variables:
    da1      (x, y) float64 -0.5074 -1.193 -0.1446 nan nan nan 0.2588 ...
    da2      (x, y) float64 nan nan nan nan nan nan nan nan nan nan nan nan ...
    da3      (x, y) float64 nan nan nan nan nan nan nan nan -0.5304 0.5848 ...

In [14]:
da1 != da2

<xarray.DataArray (x: 0, y: 0)>
array([], shape=(0, 0), dtype=bool)
Coordinates:
  * x        (x) object 
  * y        (y) int64 

In [15]:
da1 != da3

<xarray.DataArray (x: 1, y: 1)>
array([[ True]])
Coordinates:
  * x        (x) object 'b'
  * y        (y) int64 30

In [16]:
aligned = xr.align(da1, da2, da3, join="outer")

In [17]:
aligned[0] != aligned[1]

<xarray.DataArray (x: 4, y: 6)>
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [18]:
aligned[0] != aligned[2]

<xarray.DataArray (x: 4, y: 6)>
array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])
Coordinates:
  * x        (x) object 'a' 'b' 'c' 'd'
  * y        (y) int64 10 20 30 40 50 60

In [19]:
np.nonzero(np.array([True, True, False]))

(array([0, 1]),)

In [20]:
da4 = xr.DataArray([[0.0, np.nan, np.nan], [np.nan, 1.0, np.nan], [np.nan, np.nan, 2.0]], [('x', ['a', 'b', 'c']), ('y', [10, 20, 30])])
da4

<xarray.DataArray (x: 3, y: 3)>
array([[ 0., nan, nan],
       [nan,  1., nan],
       [nan, nan,  2.]])
Coordinates:
  * x        (x) <U1 'a' 'b' 'c'
  * y        (y) int64 10 20 30

In [21]:
da5 = xr.DataArray([[0.1, np.nan, np.nan], [np.nan, 0.2, np.nan], [np.nan, np.nan, 0.3]], [('x', ['c', 'd', 'e']), ('y', [40, 50, 60])])
da5

<xarray.DataArray (x: 3, y: 3)>
array([[0.1, nan, nan],
       [nan, 0.2, nan],
       [nan, nan, 0.3]])
Coordinates:
  * x        (x) <U1 'c' 'd' 'e'
  * y        (y) int64 40 50 60

In [22]:
xr.align(da4, da5, join="outer")

(<xarray.DataArray (x: 5, y: 6)>
 array([[ 0., nan, nan, nan, nan, nan],
        [nan,  1., nan, nan, nan, nan],
        [nan, nan,  2., nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd' 'e'
   * y        (y) int64 10 20 30 40 50 60, <xarray.DataArray (x: 5, y: 6)>
 array([[nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, 0.1, nan, nan],
        [nan, nan, nan, nan, 0.2, nan],
        [nan, nan, nan, nan, nan, 0.3]])
 Coordinates:
   * x        (x) object 'a' 'b' 'c' 'd' 'e'
   * y        (y) int64 10 20 30 40 50 60)

In [34]:
[(i, i%10) for i in range(1000)]

[(0, 0),
 (1, 1),
 (2, 2),
 (3, 3),
 (4, 4),
 (5, 5),
 (6, 6),
 (7, 7),
 (8, 8),
 (9, 9),
 (10, 0),
 (11, 1),
 (12, 2),
 (13, 3),
 (14, 4),
 (15, 5),
 (16, 6),
 (17, 7),
 (18, 8),
 (19, 9),
 (20, 0),
 (21, 1),
 (22, 2),
 (23, 3),
 (24, 4),
 (25, 5),
 (26, 6),
 (27, 7),
 (28, 8),
 (29, 9),
 (30, 0),
 (31, 1),
 (32, 2),
 (33, 3),
 (34, 4),
 (35, 5),
 (36, 6),
 (37, 7),
 (38, 8),
 (39, 9),
 (40, 0),
 (41, 1),
 (42, 2),
 (43, 3),
 (44, 4),
 (45, 5),
 (46, 6),
 (47, 7),
 (48, 8),
 (49, 9),
 (50, 0),
 (51, 1),
 (52, 2),
 (53, 3),
 (54, 4),
 (55, 5),
 (56, 6),
 (57, 7),
 (58, 8),
 (59, 9),
 (60, 0),
 (61, 1),
 (62, 2),
 (63, 3),
 (64, 4),
 (65, 5),
 (66, 6),
 (67, 7),
 (68, 8),
 (69, 9),
 (70, 0),
 (71, 1),
 (72, 2),
 (73, 3),
 (74, 4),
 (75, 5),
 (76, 6),
 (77, 7),
 (78, 8),
 (79, 9),
 (80, 0),
 (81, 1),
 (82, 2),
 (83, 3),
 (84, 4),
 (85, 5),
 (86, 6),
 (87, 7),
 (88, 8),
 (89, 9),
 (90, 0),
 (91, 1),
 (92, 2),
 (93, 3),
 (94, 4),
 (95, 5),
 (96, 6),
 (97, 7),
 (98, 8),
 (99, 9),
 (100, 0),

In [54]:
dims = ("x", "y")
coords_d = {"x": ("lower",  "upper"), "y": ("tens", "negative")}

shape6 = (10, 150000)
data6 = np.full(shape6, np.nan, dtype="float64")
for i in range(shape6[1]):
    data6[i%shape6[0], i] = float(i)
coords6 = {
    "lower": ("x", list(string.ascii_lowercase[:shape6[0]])), 
    "upper": ("x", list(string.ascii_uppercase[:shape6[0]])), 
    "tens": ("y", [x*10 for x in range(shape6[1])]), 
    "negative": ("y", [-x for x in range(shape6[1])])
}
da6 = xr.DataArray(data=data6, dims=dims, coords=coords6)

shape7 = (10, 300000)
data7 = np.full(shape7, np.nan, dtype="float64")
for i in range(shape7[1]):
    data7[i%shape7[0], i] = float(-i)
coords7 = {
    "lower": ("x", list(string.ascii_lowercase[shape7[0]:2*shape7[0]])), 
    "upper": ("x", list(string.ascii_uppercase[shape7[0]:2*shape7[0]])), 
    "tens": ("y", [x*10 for x in range(shape7[1], 2*shape7[1])]), 
    "negative": ("y", [-x for x in range(shape7[1], 2*shape7[1])])
}
da7 = xr.DataArray(data=data7, dims=dims, coords=coords7)

# for da in (da6, da7):
#     da.set_index(append=True, inplace=True, **coords_d)

(da6, da7)

(<xarray.DataArray (x: 10, y: 150000)>
 array([[0.00000e+00,         nan,         nan, ...,         nan,         nan,
                 nan],
        [        nan, 1.00000e+00,         nan, ...,         nan,         nan,
                 nan],
        [        nan,         nan, 2.00000e+00, ...,         nan,         nan,
                 nan],
        ...,
        [        nan,         nan,         nan, ..., 1.49997e+05,         nan,
                 nan],
        [        nan,         nan,         nan, ...,         nan, 1.49998e+05,
                 nan],
        [        nan,         nan,         nan, ...,         nan,         nan,
         1.49999e+05]])
 Coordinates:
     lower     (x) <U1 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j'
     upper     (x) <U1 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J'
     tens      (y) int64 0 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 ...
     negative  (y) int64 0 -1 -2 -3 -4 -5 -6 -7 -8 -9 -10 -11 -12 -13 -14 -15 ...
 Dimensions without coordinates

In [55]:
# da6_reloaded.close()
# da7_reloaded.close()

In [56]:
da6_file = "xarray_align_debug_da6.nc"
da6.to_netcdf(da6_file)

da7_file = "xarray_align_debug_da7.nc"
da7.to_netcdf(da7_file)

In [57]:
da6_reloaded = xr.open_dataarray(da6_file)
da7_reloaded = xr.open_dataarray(da7_file)

In [58]:
for da in (da6_reloaded, da7_reloaded):
    da.set_index(append=True, inplace=True, **coords_d)
# (da6_reloaded, da7_reloaded)

In [59]:
xr.align(da6_reloaded, da7_reloaded, join="outer")

(<xarray.DataArray (x: 20, y: 450000)>
 array([[ 0., nan, nan, ..., nan, nan, nan],
        [nan,  1., nan, ..., nan, nan, nan],
        [nan, nan,  2., ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]])
 Coordinates:
   * x         (x) MultiIndex
   - lower     (x) object 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' ...
   - upper     (x) object 'A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' ...
   * y         (y) MultiIndex
   - tens      (y) int64 0 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 ...
   - negative  (y) int64 0 -1 -2 -3 -4 -5 -6 -7 -8 -9 -10 -11 -12 -13 -14 -15 ...,
 <xarray.DataArray (x: 20, y: 450000)>
 array([[     nan,      nan,      nan, ...,      nan,      nan,      nan],
        [     nan,      nan,      nan, ...,      nan,      nan,      nan],
        [     nan,      nan,      nan, ...,      nan,      nan,      nan],
        ..

<function ndarray.var>

In [33]:
da_loaded = xr.open_dataarray("/braintree/data2/active/users/jjpr/mkgu_packaging/crcns/v2-1/V2Data1/DGrat/data.nc")
non_nan = np.nonzero(~np.isnan(da_loaded))
(da_loaded.shape, non_nan.values.shape)

((96000, 10), (2, 1772))

In [35]:
da_loaded.load()
non_nan_after_load = np.nonzero(~np.isnan(da_loaded))
(da_loaded.shape, non_nan_after_load.values.shape)

((96000, 10), (2, 1772))

In [60]:
dims = ("x", "y")
shape = (10, 5)
das = []
for j in (0, 1):
  data = np.full(shape, np.nan, dtype="float64")
  for i in range(shape[0]):
      data[i, i % shape[1]] = float(i)
  coords_d = {
      "ints": ("x", range(j*shape[0], (j+1)*shape[0])),
      "nans": ("x", np.array([np.nan] * shape[0], dtype="float64")),
      "lower": ("y", list(string.ascii_lowercase[:shape[1]]))
  }
  da = xr.DataArray(data=data, dims=dims, coords=coords_d)
  da.set_index(append=True, inplace=True, x=["ints", "nans"], y=["lower"])
  das.append(da)
nonzeros_raw = [np.nonzero(~np.isnan(da)) for da in das]
print("nonzeros_raw: ")
print(nonzeros_raw)
aligned = xr.align(*das, join="outer")
nonzeros_aligned = [np.nonzero(~np.isnan(da)) for da in aligned]
print("nonzeros_aligned: ")
print(nonzeros_aligned)
assert nonzeros_raw[0].shape == nonzeros_aligned[0].shape

nonzeros_raw: 
[<xarray.DataArray (x: 2, y: 10)>
array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])
Coordinates:
  * x        (x) MultiIndex
  - ints     (x) int64 0 1 2 3 4 5 6 7 8 9
  - nans     (x) float64 nan nan nan nan nan nan nan nan nan nan
  * y        (y) object 'a' 'b' 'c' 'd' 'e', <xarray.DataArray (x: 2, y: 10)>
array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])
Coordinates:
  * x        (x) MultiIndex
  - ints     (x) int64 10 11 12 13 14 15 16 17 18 19
  - nans     (x) float64 nan nan nan nan nan nan nan nan nan nan
  * y        (y) object 'a' 'b' 'c' 'd' 'e']
nonzeros_aligned: 
[<xarray.DataArray (x: 2, y: 0)>
array([], shape=(2, 0), dtype=int64)
Coordinates:
  * x        (x) MultiIndex
  - ints     (x) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
  - nans     (x) object nan nan nan nan nan nan nan nan nan nan nan nan nan ...
  * y        (y) object 'a' 'b' 'c' 'd' 'e', <xarray.DataArray (x: 2, y: 0)>
ar

AssertionError: 

In [61]:
das

[<xarray.DataArray (x: 10, y: 5)>
 array([[ 0., nan, nan, nan, nan],
        [nan,  1., nan, nan, nan],
        [nan, nan,  2., nan, nan],
        [nan, nan, nan,  3., nan],
        [nan, nan, nan, nan,  4.],
        [ 5., nan, nan, nan, nan],
        [nan,  6., nan, nan, nan],
        [nan, nan,  7., nan, nan],
        [nan, nan, nan,  8., nan],
        [nan, nan, nan, nan,  9.]])
 Coordinates:
   * x        (x) MultiIndex
   - ints     (x) int64 0 1 2 3 4 5 6 7 8 9
   - nans     (x) float64 nan nan nan nan nan nan nan nan nan nan
   * y        (y) object 'a' 'b' 'c' 'd' 'e', <xarray.DataArray (x: 10, y: 5)>
 array([[ 0., nan, nan, nan, nan],
        [nan,  1., nan, nan, nan],
        [nan, nan,  2., nan, nan],
        [nan, nan, nan,  3., nan],
        [nan, nan, nan, nan,  4.],
        [ 5., nan, nan, nan, nan],
        [nan,  6., nan, nan, nan],
        [nan, nan,  7., nan, nan],
        [nan, nan, nan,  8., nan],
        [nan, nan, nan, nan,  9.]])
 Coordinates:
   * x        (x) 

In [62]:
aligned

(<xarray.DataArray (x: 20, y: 5)>
 array([[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]])
 Coordinates:
   * x        (x) MultiIndex
   - ints     (x) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
   - nans     (x) object nan nan nan nan nan nan nan nan nan nan nan nan nan ...
   * y        (y) object 'a' 'b' 'c' 'd' 'e', <xarray.DataArray (x:

In [66]:
realigned = xr.align(*[da.reset_index("nans", drop=True) for da in das], join="outer")
realigned

(<xarray.DataArray (x: 20, y: 5)>
 array([[ 0., nan, nan, nan, nan],
        [nan,  1., nan, nan, nan],
        [nan, nan,  2., nan, nan],
        [nan, nan, nan,  3., nan],
        [nan, nan, nan, nan,  4.],
        [ 5., nan, nan, nan, nan],
        [nan,  6., nan, nan, nan],
        [nan, nan,  7., nan, nan],
        [nan, nan, nan,  8., nan],
        [nan, nan, nan, nan,  9.],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan]])
 Coordinates:
   * x        (x) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
   * y        (y) object 'a' 'b' 'c' 'd' 'e', <xarray.DataArray (x: 20, y: 5)>
 array([[nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan],
        [nan, nan, nan, nan,