In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
import mkgu

In [17]:
from pytest import approx

In [3]:
loaded = np.load("/Users/jjpr/dev/mkgu/tests/it_rdm.p", encoding="latin1")
loaded

array([[ 1.        ,  0.71044864,  0.28179112, ...,  0.23257068,
         0.14798986,  0.32170821],
       [ 0.71044864,  1.        ,  0.09864109, ...,  0.35317389,
         0.2825441 ,  0.56120719],
       [ 0.28179112,  0.09864109,  1.        , ...,  0.20944814,
        -0.27039143, -0.21974919],
       ..., 
       [ 0.23257068,  0.35317389,  0.20944814, ...,  1.        ,
         0.3326391 ,  0.27584533],
       [ 0.14798986,  0.2825441 , -0.27039143, ...,  0.3326391 ,
         1.        ,  0.54945685],
       [ 0.32170821,  0.56120719, -0.21974919, ...,  0.27584533,
         0.54945685,  1.        ]])

In [6]:
assy_hvm = mkgu.get_assembly(name="dicarlo.Hong2011")
assy_hvm

<xarray.NeuronRecordingAssembly (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ..., 
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ..., 
        [ 2.449372],
        [ 0.401197]],

       ..., 
       [[ 1.121319],
        [ 1.719423],
        ..., 
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ..., 
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo'

In [7]:
hvm_it_v6 = assy_hvm.sel(variation=6).sel(region="IT")
hvm_it_v6.load()
hvm_it_v6

<xarray.NeuronRecordingAssembly (neuroid: 168, presentation: 120320, time_bin: 1)>
array([[[ 0.121288],
        [-1.784021],
        ..., 
        [-0.968256],
        [ 0.183887]],

       [[ 0.512693],
        [ 0.512693],
        ..., 
        [ 2.449372],
        [ 0.401197]],

       ..., 
       [[-0.384445],
        [-0.384445],
        ..., 
        [-0.377575],
        [-0.393541]],

       [[-1.358922],
        [ 1.665531],
        ..., 
        [ 0.208243],
        [-0.358707]]], dtype=float32)
Coordinates:
  * neuroid          (neuroid) MultiIndex
  - neuroid_id       (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr              (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col              (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 8 8 6 7 5 7 7 6 6 ...
  - hemisphere       (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion        (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' 'cIT' ...
  - animal           (neuroid) object 'Chabo'

In [8]:
hvm_it_v6_obj = hvm_it_v6.multi_groupby(["category_name", "object_name"]).mean(dim="presentation").squeeze("time_bin").T
hvm_it_v6_obj

<xarray.NeuronRecordingAssembly (presentation: 64, neuroid: 168)>
array([[ 0.087381, -0.035234,  0.16607 , ..., -0.083298, -0.04096 ,  0.009889],
       [ 0.10009 ,  0.07415 ,  0.136218, ...,  0.049036, -0.040681, -0.049637],
       [ 0.196117,  0.095425, -0.012496, ...,  0.088381, -0.079695,  0.023809],
       ..., 
       [ 0.03505 ,  0.009078, -0.098099, ..., -0.030416, -0.081772, -0.185693],
       [ 0.065006,  0.072046, -0.032077, ..., -0.127431, -0.025176, -0.034318],
       [ 0.102832,  0.102089,  0.089803, ..., -0.055868, -0.108431, -0.083379]], dtype=float32)
Coordinates:
  * neuroid        (neuroid) MultiIndex
  - neuroid_id     (neuroid) object 'Chabo_L_M_5_9' 'Chabo_L_M_6_9' ...
  - arr            (neuroid) object 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' ...
  - col            (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 8 8 6 7 5 7 7 6 6 5 ...
  - hemisphere     (neuroid) object 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' 'L' ...
  - subregion      (neuroid) object 'cIT' 'cIT' 'cIT' 'cIT'

In [9]:
correlations = np.corrcoef(hvm_it_v6_obj)
correlations

array([[ 1.        ,  0.53554   ,  0.68793594, ...,  0.47855005,
         0.61849201,  0.55141304],
       [ 0.53554   ,  1.        ,  0.43818664, ...,  0.30374824,
         0.41313837,  0.35983676],
       [ 0.68793594,  0.43818664,  1.        , ...,  0.34846228,
         0.2325291 ,  0.2625039 ],
       ..., 
       [ 0.47855005,  0.30374824,  0.34846228, ...,  1.        ,
         0.33263902,  0.2758457 ],
       [ 0.61849201,  0.41313837,  0.2325291 , ...,  0.33263902,
         1.        ,  0.54945692],
       [ 0.55141304,  0.35983676,  0.2625039 , ...,  0.2758457 ,
         0.54945692,  1.        ]])

In [12]:
n = 64
n * (n-1) / 2

2016.0

In [13]:
stuff = []
for i in range(loaded.shape[0]-1):
    for j in range(i+1, loaded.shape[1]):
        stuff.append(loaded[i, j])
len(stuff)

2016

In [14]:
stuff

[0.71044863815208659,
 0.2817911227468558,
 0.14374093612357586,
 0.59090536199851906,
 0.4398622812269577,
 0.60843555342456535,
 0.26570631243552362,
 -0.24959041671064131,
 0.05144773860926416,
 0.062323725569868288,
 -0.19236776591281238,
 -0.26063759912387524,
 -0.19997780405733956,
 -0.15983594470766502,
 -0.14597256101957762,
 -0.055365848609697475,
 -0.3201257022964642,
 -0.26753183360437904,
 -0.22764926605528016,
 -0.18810289541891673,
 -0.18239544697802931,
 -0.19540045524679753,
 -0.25954836743898912,
 0.01031549956598597,
 -0.027892873261089902,
 -0.17106690627697849,
 -0.036903614465096442,
 -0.007551332478278305,
 -0.051648437087401224,
 0.068779025698616839,
 -0.088831118037066031,
 -0.078711182504940094,
 -0.15950196500285135,
 -0.21421870282492866,
 -0.17627037958403005,
 -0.082524300622625557,
 -0.2270108390880092,
 -0.17006659648546466,
 -0.076094951894696006,
 -0.22414011168879866,
 -0.23721718771294489,
 -0.28758580109652454,
 -0.12663470580063355,
 0.064852533611

In [22]:
stuff = []
for i in range(loaded.shape[0]-1):
    for j in range(i+1, loaded.shape[1]):
        print((correlations == approx(loaded[i, j], abs=1e-6)).nonzero())

(array([3, 4]), array([4, 3]))
(array([3, 6]), array([6, 3]))
(array([3, 7]), array([7, 3]))
(array([0, 3]), array([3, 0]))
(array([1, 3]), array([3, 1]))
(array([2, 3]), array([3, 2]))
(array([3, 5]), array([5, 3]))
(array([3, 8]), array([8, 3]))
(array([3, 9]), array([9, 3]))
(array([ 3, 10]), array([10,  3]))
(array([ 3, 11]), array([11,  3]))
(array([ 3, 12]), array([12,  3]))
(array([ 3, 13]), array([13,  3]))
(array([ 3, 14]), array([14,  3]))
(array([ 3, 15]), array([15,  3]))
(array([ 3, 18]), array([18,  3]))
(array([ 3, 16]), array([16,  3]))
(array([ 3, 17]), array([17,  3]))
(array([ 3, 19]), array([19,  3]))
(array([ 3, 20]), array([20,  3]))
(array([ 3, 21]), array([21,  3]))
(array([ 3, 22]), array([22,  3]))
(array([ 3, 23]), array([23,  3]))
(array([ 3, 24]), array([24,  3]))
(array([ 3, 25]), array([25,  3]))
(array([ 3, 26]), array([26,  3]))
(array([ 3, 27]), array([27,  3]))
(array([ 3, 28]), array([28,  3]))
(array([ 3, 29]), array([29,  3]))
(array([ 3, 30]), arr

In [25]:
original_objects_by_category = ['ELEPHANT_M', 'GORILLA', 'LIONESS', 'TURTLE_L', 'bear', 'blCow', 'breed_pug', 'hedgehog', 'BAHRAIN', 'CGTG_L', 'DTUG_L', 'MQUEEN_L', 'SISTER_L', 'cruiser', 'motoryacht', 'support', 'Beetle', 'alfa155', 'astra', 'bmw325', 'bora_a', 'celica', 'clio', 'z3', '_001', '_004', '_008', '_010', '_011', '_014', '_031', '_033', 'face0001', 'face0002', 'face0003', 'face0004', 'face0005', 'face0006', 'face0007', 'face0008', 'Apple_Fruit_obj', 'Apricot_obj', 'Peach_obj', 'Pear_obj', 'Strawberry_obj', 'raspberry_obj', 'walnut_obj', 'watermelon_obj', '_01_Airliner_2jetEngines', '_05_future', '_19_flyingBoat', 'f16', 'junkers88', 'mig29', 'rdbarren', 'sopwith', '_08', '_10', '_11', '_12', '_18', '_37', '_38', '_44']
original_objects_by_category

['ELEPHANT_M',
 'GORILLA',
 'LIONESS',
 'TURTLE_L',
 'bear',
 'blCow',
 'breed_pug',
 'hedgehog',
 'BAHRAIN',
 'CGTG_L',
 'DTUG_L',
 'MQUEEN_L',
 'SISTER_L',
 'cruiser',
 'motoryacht',
 'support',
 'Beetle',
 'alfa155',
 'astra',
 'bmw325',
 'bora_a',
 'celica',
 'clio',
 'z3',
 '_001',
 '_004',
 '_008',
 '_010',
 '_011',
 '_014',
 '_031',
 '_033',
 'face0001',
 'face0002',
 'face0003',
 'face0004',
 'face0005',
 'face0006',
 'face0007',
 'face0008',
 'Apple_Fruit_obj',
 'Apricot_obj',
 'Peach_obj',
 'Pear_obj',
 'Strawberry_obj',
 'raspberry_obj',
 'walnut_obj',
 'watermelon_obj',
 '_01_Airliner_2jetEngines',
 '_05_future',
 '_19_flyingBoat',
 'f16',
 'junkers88',
 'mig29',
 'rdbarren',
 'sopwith',
 '_08',
 '_10',
 '_11',
 '_12',
 '_18',
 '_37',
 '_38',
 '_44']

In [27]:
hvm_it_v6_obj.sortby([hvm_it_v6_obj["category_name"], hvm_it_v6_obj["object_name"]])["object_name"]

<xarray.NeuronRecordingAssembly 'object_name' (presentation: 64)>
array(['bear', 'cow', 'dog', 'elephant', 'gorilla', 'hedgehog', 'lioness',
       'turtle', 'ship0', 'ship1', 'ship2', 'ship3', 'ship4', 'ship5', 'ship6',
       'ship7', 'car_alfa', 'car_astra', 'car_beetle', 'car_bmw', 'car_bora',
       'car_celica', 'car_clio', 'car_z3', 'chair0', 'chair1', 'chair2',
       'chair3', 'chair4', 'chair5', 'chair6', 'chair7', 'face0', 'face1',
       'face2', 'face3', 'face4', 'face5', 'face6', 'face7', 'apple', 'apricot',
       'peach', 'pear', 'raspberry', 'strawberry', 'walnut', 'watermelon',
       'airplane0', 'airplane1', 'airplane2', 'airplane3', 'airplane4',
       'airplane5', 'airplane6', 'airplane7', 'table0', 'table1', 'table2',
       'table3', 'table4', 'table5', 'table6', 'table7'], dtype=object)
Coordinates:
    time_bin       object (70, 170)
  * presentation   (presentation) MultiIndex
  - category_name  (presentation) object 'Animals' 'Animals' 'Animals' ...
  - obje

In [ ]:
    assert correlations.shape == (64, 64)
    assert correlations == approx(loaded, abs=1e-6)