In [1]:
import dldata.stimulus_sets.hvm as hvm

Can't import h5py
Can't import separate mcc package
Can't import asgd.


/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/sklearn/lda.py:6: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be remov

In [2]:
import xarray as xr

In [3]:
import random

In [4]:
from collections import OrderedDict

In [5]:
from pytest import approx

In [29]:
import pandas as pd

In [44]:
import numpy as np

In [6]:
dl_hvm = hvm.HvMWithDiscfade()

In [7]:
dl_hvm_neu = dl_hvm.get_neuronal_feature_reps(sort_by_meta=True)

/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/tabular/utils.py:81: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if s != None:
/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/tabular/spreadsheet.py:1467: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  for k in Names if deletecols(L[k][0:0], keycols) != None])


common attributes, forcing a renaming ...
Using default renamer ...


/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/tabular/spreadsheet.py:1493: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if deletecols(L[j][D[i]], keycols) != None])


('Replacing columns', ['rxz', 'rxy', 'ryz'])


/Users/jjpr/anaconda/envs/dldata/lib/python2.7/site-packages/tables/leaf.py:394: PerformanceWarning: The Leaf ``/spk`` is exceeding the maximum recommended rowsize (104857600 bytes);
be ready to see PyTables asking for *lots* of memory and possibly slow
I/O.  You may want to reduce the rowsize by trimming the value of
dimensions that are orthogonal (and preferably close) to the *main*
dimension of this leave.  Alternatively, in case you have specified a
very small/large chunksize, you may want to increase/decrease it.
  PerformanceWarning)


In [8]:
dl_meta = dl_hvm.meta

In [9]:
dl_meta_neu = dl_hvm.meta_neu

In [10]:
xr_hvm = xr.open_dataarray("/Users/jjpr/.mkgu/data/dicarlo.Hong2011/hvm_neuronal_features.nc")

In [11]:
xr_hvm

<xarray.DataArray (neuroid: 296, presentation: 268800, time_bin: 1)>
[79564800 values with dtype=float32]
Coordinates:
    neuroid_id      (neuroid) object u'Chabo_L_M_5_9' u'Chabo_L_M_6_9' ...
    arr             (neuroid) object u'M' u'M' u'M' u'M' u'M' u'M' u'M' u'M' ...
    time_bin_start  (time_bin) int64 70
    col             (neuroid) int64 9 9 8 9 8 8 7 7 5 6 4 9 9 9 9 9 8 7 9 6 ...
    hemisphere      (neuroid) object u'L' u'L' u'L' u'L' u'L' u'L' u'L' u'L' ...
    subregion       (neuroid) object u'cIT' u'cIT' u'cIT' u'cIT' u'cIT' ...
    animal          (neuroid) object u'Chabo' u'Chabo' u'Chabo' u'Chabo' ...
    y               (neuroid) float64 0.2 0.6 0.2 1.0 0.6 1.0 1.8 1.0 1.8 ...
    x               (neuroid) float64 1.8 1.8 1.4 1.8 1.4 1.4 1.0 1.0 0.2 ...
    time_bin_end    (time_bin) int64 170
    region          (neuroid) object u'IT' u'IT' u'IT' u'IT' u'IT' u'IT' ...
    row             (neuroid) int64 5 6 5 7 6 7 9 7 9 8 9 2 1 3 6 7 6 6 8 5 ...
    image_id     

In [12]:
[s.shape for s in dl_hvm_neu.values()]

[(28, 640, 296), (51, 2560, 296), (47, 2560, 296)]

In [13]:
dl_axes = ["repetition", "image", "neuroid"]

In [14]:
dl_hvm_neu.keys()

['V0', 'V3', 'V6']

In [15]:
dl_meta.dtype

dtype((numpy.record, [('obj', 'S24'), ('rxz', '<f8'), ('rxy', '<f8'), ('ryz', '<f8'), ('ty', '<f8'), ('tz', '<f8'), ('s', '<f8'), ('bg_id', 'S40'), ('size', '<i8'), ('var', 'S2'), ('_id', 'S43'), ('filename', 'S236'), ('id', 'S40'), ('category', 'S7'), ('rxz_semantic', '<f8'), ('rxy_semantic', '<f8'), ('ryz_semantic', '<f8')]))

In [16]:
dl_meta["id"][28]

'768108628bf1edd1a2db3effb28032235d6407a2'

In [17]:
dl_meta_neu.dtype

dtype((numpy.record, [('animal', 'S5'), ('region', 'S2'), ('arr', 'S1'), ('row', '<i8'), ('col', '<i8'), ('y', '<f8'), ('x', '<f8')]))

In [18]:
dl_meta_neu["animal"][151]

'Tito'

In [33]:
def get_dl_sample(dl_hvm_neu, dl_meta, dl_meta_neu):
    sample = {}
    var = random.choice(dl_hvm_neu.keys())
    sample["dl_variation"] = var
    neu = dl_hvm_neu[var]
    dl_meta_var = dl_meta[dl_meta['var'] == var]
    
    rep = sample["dl_repetition_idx"] = random.randrange(neu.shape[0])
    
    im = sample["dl_image_idx"] = random.randrange(neu.shape[1])
    sample["dl_image_id"] = dl_meta_var["id"][im]
    
    n = sample["dl_neuroid_idx"] = random.randrange(neu.shape[2])
    sample["dl_neuroid_animal"] = dl_meta_neu["animal"][n]
    sample["dl_neuroid_hemisphere"] = "L"
    sample["dl_neuroid_arr"] = dl_meta_neu["arr"][n]
    sample["dl_neuroid_row"] = dl_meta_neu["row"][n]
    sample["dl_neuroid_col"] = dl_meta_neu["col"][n]
    
    val = sample["dl_value"] = neu[rep, im, n]
    return sample
sample = get_dl_sample(dl_hvm_neu, dl_meta, dl_meta_neu)
sample

{'dl_image_id': 'db242e57d16849450c4ca0d41f00ce2d2ba5ae2a',
 'dl_image_idx': 508,
 'dl_neuroid_animal': 'Tito',
 'dl_neuroid_arr': 'A',
 'dl_neuroid_col': 2,
 'dl_neuroid_hemisphere': 'L',
 'dl_neuroid_idx': 189,
 'dl_neuroid_row': 4,
 'dl_repetition_idx': 11,
 'dl_value': -0.69440776,
 'dl_variation': 'V0'}

In [20]:
def coords_for_dim(xr_data, dim, exclude_indexes=True):
    result = OrderedDict()
    for key, value in xr_data.coords.variables.items():
        only_this_dim = value.dims == (dim,)
        exclude_because_index = exclude_indexes and isinstance(value, xr.IndexVariable)
        if only_this_dim and not exclude_because_index:
            result[key] = value
    return result

In [21]:
def gather_indexes(xr_data):
    """This is only necessary as long as xarray cannot persist MultiIndex to netCDF.  """
    coords_d = {}
    for dim in xr_data.dims:
        coords = coords_for_dim(xr_data, dim)
        if coords:
            coords_d[dim] = coords.keys()
    if coords_d:
        xr_data.set_index(append=True, inplace=True, **coords_d)
    return xr_data

In [22]:
xr_hvm = gather_indexes(xr_hvm)

In [23]:
def get_xr_sample(xr_hvm, sample):
    xr_sample = xr_hvm.sel(image_id=sample["dl_image_id"], 
                      repetition=sample["dl_repetition_idx"],
                      animal=sample["dl_neuroid_animal"],
                      hemisphere=sample["dl_neuroid_hemisphere"],
                      arr=sample["dl_neuroid_arr"],
                      row=sample["dl_neuroid_row"],
                      col=sample["dl_neuroid_col"])
    return xr_sample
xr_sample = get_xr_sample(xr_hvm, sample)
xr_sample

<xarray.DataArray (neuroid: 1, stimulus: 1, time_bin: 1)>
array([[[-0.996739]]], dtype=float32)
Coordinates:
  * stimulus        (stimulus) int64 41
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object u'Tito_L_M_0_4'
  - subregion       (neuroid) object u'pIT'
  - y               (neuroid) float64 -1.8
  - x               (neuroid) float64 -0.2
  - region          (neuroid) object u'IT'
  * time_bin        (time_bin) MultiIndex
  - time_bin_start  (time_bin) int64 70
  - time_bin_end    (time_bin) int64 170

In [24]:
xr_sample.values[0, 0, 0] == approx(sample["dl_value"], abs=1e-6)

True

In [25]:
xr_hvm.load()

<xarray.DataArray (neuroid: 296, presentation: 268800, time_bin: 1)>
array([[[ 0.060929],
        [-0.686162],
        ..., 
        [-0.968256],
        [ 0.183887]],

       [[-0.725592],
        [ 0.292777],
        ..., 
        [ 2.449372],
        [ 0.401197]],

       ..., 
       [[ 1.121319],
        [ 1.719423],
        ..., 
        [ 0.800551],
        [-0.019874]],

       [[-0.518903],
        [ 0.696196],
        ..., 
        [-0.603347],
        [-0.175979]]], dtype=float32)
Coordinates:
  * presentation    (presentation) MultiIndex
  - image_id        (presentation) object u'8a72e2bfdb8c267b57232bf96f069374d5b21832' ...
  - repetition      (presentation) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
  - stimulus        (presentation) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
  * neuroid         (neuroid) MultiIndex
  - neuroid_id      (neuroid) object u'Chabo_L_M_5_9' u'Chabo_L_M_6_9' ...
  - arr             (neuroid) object u'M' u'M' u'M' u'M' u'M' u'M' u'M' u'M' 

In [34]:
samples = []
for i in range(1000):
    sample = get_dl_sample(dl_hvm_neu, dl_meta, dl_meta_neu) 
    xr_sample = get_xr_sample(xr_hvm, sample)
    sample["xr_sample"] = xr_sample
    samples.append(sample)

In [35]:
errors = []
for sample in samples:
    try:
        dl_value = sample["dl_value"]
        xr_value = sample["xr_sample"].values[0, 0, 0] 
        print(dl_value, xr_value)
        if xr_value != approx(dl_value, abs=1e-6):
            print(sample)
            errors.append(sample)
    except IndexError:
        print(dl_value)
        errors.append(sample)

(-0.61939675, -0.61939675)
(0.51070434, 0.51070434)
(0.10322264, 0.10322264)
(-0.69525141, -0.69525141)
(-1.3130871, -1.3130871)
(-1.872653, -1.872653)
(-1.5418377, -1.5418377)
(-0.36553365, -0.36553365)
(1.9079622, 1.9079622)
(0.32348523, 0.32348523)
(-0.05386496, -0.05386496)
(-0.65768099, -0.65768099)
(0.46570408, 0.46570408)
(-0.064900592, -0.064900592)
(0.39230689, 0.39230689)
(2.8037624, 2.8037624)
(-0.72313088, -0.72313088)
(0.14842062, 0.14842062)
(0.4484697, 0.4484697)
(0.49917316, 0.49917316)
(-0.44880751, -0.44880751)
(-1.4149538, -1.4149538)
(-0.82885963, -0.82885963)
(-0.014211657, -0.014211657)
(-0.18886924, -0.18886924)
(0.21405879, 0.21405879)
(0.57301897, 0.57301897)
(0.79684258, 0.79684258)
(0.30699074, 0.30699074)
(1.0789884, 1.0789884)
(0.47498477, 0.47498477)
(0.39601612, 0.39601612)
(-2.586072, -2.586072)
(-0.62541872, -0.62541872)
(1.4002517, 1.4002517)
(-0.071719624, -0.071719624)
(-1.1646674, -1.1646674)
(-0.60391086, -0.60391086)
(0.90325874, 0.90325874)
(0.00

In [36]:
len(errors)

0

In [37]:
[(s["dl_value"], s["xr_sample"].values) for s in samples]

[(-0.61939675, array([[[-0.61939675]]], dtype=float32)),
 (0.51070434, array([[[ 0.51070434]]], dtype=float32)),
 (0.10322264, array([[[ 0.10322264]]], dtype=float32)),
 (-0.69525141, array([[[-0.69525141]]], dtype=float32)),
 (-1.3130871, array([[[-1.31308711]]], dtype=float32)),
 (-1.872653, array([[[-1.87265301]]], dtype=float32)),
 (-1.5418377, array([[[-1.54183769]]], dtype=float32)),
 (-0.36553365, array([[[-0.36553365]]], dtype=float32)),
 (1.9079622, array([[[ 1.9079622]]], dtype=float32)),
 (0.32348523, array([[[ 0.32348523]]], dtype=float32)),
 (-0.05386496, array([[[-0.05386496]]], dtype=float32)),
 (-0.65768099, array([[[-0.65768099]]], dtype=float32)),
 (0.46570408, array([[[ 0.46570408]]], dtype=float32)),
 (-0.064900592, array([[[-0.06490059]]], dtype=float32)),
 (0.39230689, array([[[ 0.39230689]]], dtype=float32)),
 (2.8037624, array([[[ 2.80376244]]], dtype=float32)),
 (-0.72313088, array([[[-0.72313088]]], dtype=float32)),
 (0.14842062, array([[[ 0.14842062]]], dtype

In [38]:
samples

[{'dl_image_id': '9d04359644201352037782246614a060beb35bdf',
  'dl_image_idx': 367,
  'dl_neuroid_animal': 'Chabo',
  'dl_neuroid_arr': 'M',
  'dl_neuroid_col': 0,
  'dl_neuroid_hemisphere': 'L',
  'dl_neuroid_idx': 127,
  'dl_neuroid_row': 8,
  'dl_repetition_idx': 14,
  'dl_value': -0.61939675,
  'dl_variation': 'V0',
  'xr_sample': <xarray.DataArray (neuroid: 1, stimulus: 1, time_bin: 1)>
  array([[[-0.619397]]], dtype=float32)
  Coordinates:
    * stimulus        (stimulus) int64 191
    * neuroid         (neuroid) MultiIndex
    - neuroid_id      (neuroid) object u'Chabo_L_M_8_0'
    - subregion       (neuroid) object u'pIT'
    - y               (neuroid) float64 1.4
    - x               (neuroid) float64 -1.8
    - region          (neuroid) object u'IT'
    * time_bin        (time_bin) MultiIndex
    - time_bin_start  (time_bin) int64 70
    - time_bin_end    (time_bin) int64 170},
 {'dl_image_id': 'b5e3a8c2745ebec3513201aaa9f66682669f3d4f',
  'dl_image_idx': 352,
  'dl_neuroid

In [39]:
errors

[]

In [40]:
xr_hvm.shape

(296, 268800, 1)

In [41]:
df_errors = pd.DataFrame(errors)
df_errors

Empty DataFrame
Columns: []
Index: []

In [31]:
df_errors["dl_variation"].unique()

array(['V6', 'V3'], dtype=object)

In [32]:
df_samples = pd.DataFrame(samples)
df_samples

dl_image_id  dl_image_idx dl_neuroid_animal  \
0    082f0e5cc064bfbdf7a9679e1aca6d74503260d4          1359              Tito   
1    40c8caefe8e31133985747354d4d2bedd69df540           561              Tito   
2    d74fb40d88d6b4139346e0be3236da980a880c3c           787              Tito   
3    6d15e65826ca09ea0e51c25c8005c1fdcf542cfb           273              Tito   
4    8bac49738ba85900e6395d8d2a75d0e53efa64b5          2360             Chabo   
5    1e9ff75c2c5794b644aeb582a95ee41eda8f8d29          2326              Tito   
6    ad09855a7755701a8d9c11fde725ad76044b0cdd           427              Tito   
7    b66671aed7c38cf4ecf869694d3532ae09802c55           277             Chabo   
8    a27cf585cef0941973572d5265af974c78dcb036           536             Chabo   
9    b60675f2b54af66bb192ef883ea5242adbbfdeae           300              Tito   
10   63889f5983235823d5126fd0903bc8b30ed41a0d          1383             Chabo   
11   106abf0c8b70ac7717b79a0432137c0ee7c2d3c0           430             Chabo   
12   691384450355c07ad084613a08a018ae8e1eebb2             1              Tito   
13   f9c4709bf115b6a5ebfb21d8642760b3947e1587          1064              Tito   
14   d61fbfe60406925ed887cd46696a38915401fd10          1544             Chabo   
15   a22aa0af2fef1f0a648f79aba5fa22bedc6c1c95          1956              Tito   
16   2970df86fb9706eb1ef066a7120049eb7bb8656e            95             Chabo   
17   de32e3f47daaa60cbca95c4cbcfbec1372eb91a0          1399              Tito   
18   1d9e426371ba9061f468491439df06ccebdfa76d          1682             Chabo   
19   cd8c4d602c8c87b580270c27ccb4a74a806bfd31          2138              Tito   
20   28b903af5db5a703437b44715c81ef50f8b3e897           365              Tito   
21   e2821515707ddbd23cc04d085b25c975bbb4bd28           673             Chabo   
22   7859a3f7adbe745dda45c1e1294fe15520480a8c          2411              Tito   
23   3d858b4bc82f5d02fbf800e1c66a1e9be99cf714           404             Chabo   
24   83baa8b3551ca365149059b778ab2bf6521596f9           705             Chabo   
25   4c18e3050e18b581c303cd21e8e24c10cfefbd99           877              Tito   
26   36b1652f43aedf23e39f351fd931ab0cb4c410b5           350             Chabo   
27   fe42df2a3d9a7b285d3e4478a299a4acb6cfa6a7          2350             Chabo   
28   45564088770cdc6e87cdd8bfd161465ba653163a          1488             Chabo   
29   bb1c929420d8566cdbcc2e46e88b8e37b42db522           702              Tito   
..                                        ...           ...               ...   
970  612929286e43af83b7c3663adadab6f05655351c           192              Tito   
971  6997bb3d5bef2f6f9d6cfbdcaab1444680a44cb0            92             Chabo   
972  42b1902dafba9ba9def79ea65bf53aa25bf2704c           186             Chabo   
973  2ba5a992fc991d89599ee947da8064c4717d7327           452              Tito   
974  7cd382ea155d67227b21efb511eb457d9a5d186d           514             Chabo   
975  9b35887ca300b07ad46f5572bddf59417f27b55d           354              Tito   
976  d1bfc7f4621499838d037519e743dc1ab0eba912           337              Tito   
977  a7a31e65e2770c7a503988835c24aeab689abf47           130             Chabo   
978  6c7daecc1e61141c7b75d549ac3d3d05e51056ab           511              Tito   
979  64b31e4fc9af784e16ea3d2e2c48dd1eda5a261e            43              Tito   
980  025f6fd6e41e19a963994f40a407b552364e7e20            51              Tito   
981  3e52a117766d348d8bcafa3f6b7bb2fc7b86a69d           380              Tito   
982  28e31e574f90690adc228f38e4fff0a192bf8645           592              Tito   
983  4d1697209942afa1fc5a3d1394af394a8c6bf89b           600             Chabo   
984  9298606f65e0329d01678060669c4b11603854f3           323             Chabo   
985  c6fb4f35719f0f205f5ad65f4fd2794212c5d139           594             Chabo   
986  d7efac271ed7805cde8ee483970d3e3881db4033           506             Chabo   
987  42530b90eb5a8d8c706f0d3da438194e53fe0efe           295      

In [45]:
loaded = np.load("/Users/jjpr/dev/mkgu/tests/it_rdm.p", encoding="latin1")
loaded

array([[ 1.        ,  0.71044864,  0.28179112, ...,  0.23257068,
         0.14798986,  0.32170821],
       [ 0.71044864,  1.        ,  0.09864109, ...,  0.35317389,
         0.2825441 ,  0.56120719],
       [ 0.28179112,  0.09864109,  1.        , ...,  0.20944814,
        -0.27039143, -0.21974919],
       ..., 
       [ 0.23257068,  0.35317389,  0.20944814, ...,  1.        ,
         0.3326391 ,  0.27584533],
       [ 0.14798986,  0.2825441 , -0.27039143, ...,  0.3326391 ,
         1.        ,  0.54945685],
       [ 0.32170821,  0.56120719, -0.21974919, ...,  0.27584533,
         0.54945685,  1.        ]])

In [46]:
loaded.shape

(64, 64)