In [1]:
import sys
sys.path.append('/home/shashi/projects/brain_score/candidate_models')
sys.path.append('/home/shashi/projects/brain_score/brain-score')
sys.path.append('/home/shashi/projects/brain_score/model-tools')
sys.path.append('/home/shashi/projects/brain_score/brainio_collection')
sys.path.append('/home/shashi/projects/brain_score/tf-models/research/slim')

In [2]:
import warnings
warnings.simplefilter("ignore")

In [3]:
from candidate_models.model_commitments import MLSearchPool
from brainscore.benchmarks import benchmark_pool
import numpy as np
import brainscore


For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



# Example on Object Array Dataset

In [4]:
brain_translated_pool = MLSearchPool(target_img_size=28, search_image_size=224)
identifier = 'vgg-16'
model = brain_translated_pool[identifier]

benchmark = benchmark_pool['klab.Zhang2018.ObjSearch-objarr']
score = benchmark(model)

print(score)

vgg-16 is accessed again and reloaded


Instructions for updating:
Colocations handled automatically by placer.


Using TensorFlow backend.
comparing with human data: 100%|██████████| 15/15 [00:03<00:00,  4.75it/s]


<xarray.Score (aggregation: 2)>
array([0.941507, 0.005717])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:      <xarray.Score (aggregation: 2)>\narray([0.415299, 0.005717])\nC...
    ceiling:  <xarray.Score (aggregation: 2)>\narray([0.4411,    nan])\nCoord...


# Example on Waldo Dataset

In [5]:
# Shashi: Martin how we can change the batch size for activation model
# Actual target_img_size should be 28 and search_img_size be 1024
# But due to memory issues I have resized it show as to verify if the benchmark is working or not..

brain_translated_pool = MLSearchPool(target_img_size=16, search_image_size=580)
identifier = 'vgg-16'
model = brain_translated_pool[identifier]

benchmark = benchmark_pool['klab.Zhang2018.VisualSearch-waldo']
score = benchmark(model)

print(score)

vgg-16 is accessed again and reloaded
comparing with human data: 100%|██████████| 15/15 [00:05<00:00,  2.70it/s]

<xarray.Score (aggregation: 2)>
array([0.767607, 0.00801 ])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:      <xarray.Score (aggregation: 2)>\narray([0.270121, 0.00801 ])\nC...
    ceiling:  <xarray.Score (aggregation: 2)>\narray([0.3519,    nan])\nCoord...


# Example on Natural Design Dataset

In [6]:
# Shashi: Martin how we can change the batch size for activation model
# Actual target_img_size should be 28 and search_img_size be 1024
# But due to memory issues I have resized it show as to verify if the benchmark is working or not..

brain_translated_pool = MLSearchPool(target_img_size=16, search_image_size=580)
identifier = 'vgg-16'
model = brain_translated_pool[identifier]

benchmark = benchmark_pool['klab.Zhang2018.VisualSearch-naturaldesign']
score = benchmark(model)

print(score)

vgg-16 is accessed again and reloaded
comparing with human data: 100%|██████████| 15/15 [00:12<00:00,  1.22it/s]

<xarray.Score (aggregation: 2)>
array([0.596883, 0.009701])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:      <xarray.Score (aggregation: 2)>\narray([0.235948, 0.009701])\nC...
    ceiling:  <xarray.Score (aggregation: 2)>\narray([0.3953,    nan])\nCoord...
